[rospy.client][INFO] 2019-06-02 15:03:26,902: init_node, name[/waypoint_updater], pid[13974]
[xmlrpc][INFO] 2019-06-02 15:03:26,903: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-02 15:03:26,903: Started XML-RPC server [http://a917bedbf8a8:44041/]
[rospy.impl.masterslave][INFO] 2019-06-02 15:03:26,904: _ready: http://a917bedbf8a8:44041/
[rospy.init][INFO] 2019-06-02 15:03:26,904: ROS Slave URI: [http://a917bedbf8a8:44041/]
[xmlrpc][INFO] 2019-06-02 15:03:26,905: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-02 15:03:26,908: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-02 15:03:27,008: registered with master
[rospy.rosout][INFO] 2019-06-02 15:03:27,008: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-02 15:03:27,017: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-02 15:03:27,019: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-06-02 15:03:27,077: topic[/current_pose] adding connection to [http://a917bedbf8a8:46451/], count 0
[rospy.internal][INFO] 2019-06-02 15:03:27,121: topic[/final_waypoints] adding connection to [/styx_server], count 0
[rospy.internal][INFO] 2019-06-02 15:03:27,196: topic[/base_waypoints] adding connection to [http://a917bedbf8a8:43097/], count 0
[rospy.internal][INFO] 2019-06-02 15:03:27,244: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-02 15:03:27,264: topic[/final_waypoints] adding connection to [/pure_pursuit], count 1
[rospy.internal][INFO] 2019-06-02 15:03:32,111: topic[/traffic_waypoint] adding connection to [http://a917bedbf8a8:45593/], count 0
[rospy.core][INFO] 2019-06-02 15:04:47,997: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2019-06-02 15:04:48,027: Unable to initiate TCP/IP socket to a917bedbf8a8:35635 (http://a917bedbf8a8:46451/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2019-06-02 15:04:48,059: topic[/final_waypoints] removing connection to /styx_server
[rospy.internal][INFO] 2019-06-02 15:04:48,059: topic[/final_waypoints] removing connection to /pure_pursuit
[rospy.internal][INFO] 2019-06-02 15:04:48,059: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-02 15:04:48,060: topic[/traffic_waypoint] removing connection to http://a917bedbf8a8:45593/
[rospy.internal][INFO] 2019-06-02 15:04:48,061: topic[/base_waypoints] removing connection to http://a917bedbf8a8:43097/
[rospy.internal][INFO] 2019-06-02 15:04:48,061: topic[/current_pose] removing connection to http://a917bedbf8a8:46451/
[rospy.impl.masterslave][INFO] 2019-06-02 15:04:48,062: signal-2
[rospy.core][INFO] 2019-06-02 15:04:48,646: signal_shutdown [atexit]
