[rospy.client][INFO] 2019-06-02 14:28:03,669: init_node, name[/waypoint_updater], pid[9798]
[xmlrpc][INFO] 2019-06-02 14:28:03,669: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-02 14:28:03,670: Started XML-RPC server [http://a917bedbf8a8:40243/]
[rospy.init][INFO] 2019-06-02 14:28:03,670: ROS Slave URI: [http://a917bedbf8a8:40243/]
[rospy.impl.masterslave][INFO] 2019-06-02 14:28:03,671: _ready: http://a917bedbf8a8:40243/
[xmlrpc][INFO] 2019-06-02 14:28:03,671: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-02 14:28:03,672: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-02 14:28:03,771: registered with master
[rospy.rosout][INFO] 2019-06-02 14:28:03,771: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-02 14:28:03,774: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-02 14:28:03,777: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-06-02 14:28:03,802: topic[/current_pose] adding connection to [http://a917bedbf8a8:36611/], count 0
[rospy.internal][INFO] 2019-06-02 14:28:03,815: topic[/base_waypoints] adding connection to [http://a917bedbf8a8:39989/], count 0
[rospy.internal][INFO] 2019-06-02 14:28:03,915: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-02 14:28:03,950: topic[/final_waypoints] adding connection to [/styx_server], count 0
[rospy.internal][INFO] 2019-06-02 14:28:04,100: topic[/final_waypoints] adding connection to [/pure_pursuit], count 1
[rospy.internal][INFO] 2019-06-02 14:28:07,030: topic[/traffic_waypoint] adding connection to [http://a917bedbf8a8:36249/], count 0
[rospy.core][INFO] 2019-06-02 14:29:10,816: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2019-06-02 14:29:10,821: Unable to initiate TCP/IP socket to a917bedbf8a8:44847 (http://a917bedbf8a8:36249/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2019-06-02 14:29:10,823: topic[/final_waypoints] removing connection to /styx_server
[rospy.internal][INFO] 2019-06-02 14:29:10,824: topic[/final_waypoints] removing connection to /pure_pursuit
[rospy.internal][INFO] 2019-06-02 14:29:10,824: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-02 14:29:10,826: topic[/traffic_waypoint] removing connection to http://a917bedbf8a8:36249/
[rospy.internal][INFO] 2019-06-02 14:29:10,826: topic[/base_waypoints] removing connection to http://a917bedbf8a8:39989/
[rospy.internal][INFO] 2019-06-02 14:29:10,827: topic[/current_pose] removing connection to http://a917bedbf8a8:36611/
[rospy.impl.masterslave][INFO] 2019-06-02 14:29:10,828: signal-2
[rospy.core][INFO] 2019-06-02 14:29:10,961: signal_shutdown [atexit]
